### ISSUE TITLE
metrics for app servers

### ISSUE THREAD

**Issue by jamieklassen** [jamieklassen/demo#4]
Possible solutions include Nagios or Zabbix.

**Comment by jamieklassen** [comment]
@segalm999 exciting to see a working example with prometheus/grafana. Still need to figure out how to persist this configuration, as the grafana server is running in a docker container with ephemeral disk.
<img width="1662" alt="screen shot 2018-01-05 at 4 34 53 pm" src="https://user-images.githubusercontent.com/898783/34629525-74669dfc-f236-11e7-914a-f76c50503108.png">

**Comment by segalm999** [comment]
Nice!
