### ISSUE TITLE
move infrastructure steps into their own pipeline

### ISSUE THREAD

**Issue by jamieklassen** [jamieklassen/demo#8]
might also be useful for the jenkins server to start docker-compose on startup as well. This will improve the running time of pipeline runs, and is a more logical separation of duties.

**Comment by jamieklassen** [comment]
I am struck by the question of whether to run the app pipeline each time the infrastructure pipeline runs. To clarify, should I redeploy the app and run all the load tests, etc each time I change the gold image? @segalm999 curious about your thoughts.

**Comment by segalm999** [comment]
I think so. I mean you've changed the underlying infrastructure so I think
you should run all processes that have a dependency on that infrastructure.

At the end of the day it's cheap so why not. If cost is an issue then we
can make cost/risk trade offs.

**Comment by jamieklassen** [comment]
might be another suitable case for some kind of canary deploy -- seems like a shame to break a working app by changing the gold image. For the time being, though, it should be possible to use a post-build step in the infrastructure pipeline that calls the app pipeline.

**Comment by jamieklassen** [comment]
Resolved by a1423e4.
